version: "3.4"
services:
  organizer:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT = ${PORT}
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/organizer/dev
      - exclude:/usr/local/apps/organizer/dev/node_modules/
volumes:
  exclude:
