FROM node:16-alpine
WORKDIR /usr/local/apps/organizer

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/organizer/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/organizer/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

EXPOSE ${PORT}

CMD ["npm", "run", "import:all", "npm", "run", "start:watch"]